@echo off
python build_creature_health_csv.py
python build_creature_health_f_csv.py
python build_creature_names_csv.py
python build_creature_resistance_csv.py
python build_creature_resistance_f_csv.py
pause